---
version: '3'
services:
  server:
    build: .
    image: index.docker.io/oaklabs/component-shutdown:latest
    network_mode: host
    environment:
      NODE_ENV: 'development'
      PLATFORM_HOST: '192.168.0.66:443'
      SHUTDOWN_TIME: '0 0 18 * * *'
      TZ: 'America/Los_Angeles'
  
